import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useGetTweetsQuery, useGetUsersQuery } from "../generated/graphql";

const Home: NextPage = () => {
  const { isSuccess, data } = useGetTweetsQuery();
  const response = useGetUsersQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isSuccess &&
          data?.app_user.map((user, index) => {
            return (
              <div key={index}>
                <p>{user.username}</p>
                <ul>
                  {user.tweets.map((tweet, index) => {
                    return <li key={index}>{tweet.content}</li>;
                  })}
                </ul>
              </div>
            );
          })}
      </main>
    </div>
  );
};

export default Home;
